// docs/VALIDATION.md, checks V1-V12: Paradise against the Camp Fire of 8 November 2018.
//
// The ranges were written down before the model produced a single number, and nothing here
// moves one. A check that misses is marked `it.fails` with its cause named, so the suite goes
// red the day it starts passing and the marker can be deleted -- which is the point.
//
// The scenarios judged here are the files public/scenarios/*.json that the app itself serves,
// generated by tools/scenarios.ts. Judging a second copy of the same intent would prove only
// that the copy agrees with itself.

import { beforeAll, describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { createSim, metrics } from '../src/core/sim.ts';
import { maxFlow } from '../src/core/maxflow.ts';
import { normalizeScenario, resolveParams } from '../src/core/scenario.ts';
import { classOf, FLAG } from '../src/core/city.ts';
import { CLASS_CODE } from '../src/core/params.ts';
import { publicCity, run } from './helpers.ts';
import type { Metrics, Scenario } from '../src/core/types.ts';

const HOUR = 3600;
const ARTERIES = ['Skyway', 'Clark Road', 'Neal Road', 'Pentz Road'];

/** 'bare' is the city as the preprocessor left it, with no scenario file -- the network V2
 *  and V4 are written against. Everything else is a preset the app actually serves. */
const preset = (name: string): Scenario =>
  name === 'bare'
    ? normalizeScenario({ city: 'paradise', routing: { informed: 0 } })
    : normalizeScenario(JSON.parse(readFileSync(`public/scenarios/${name}.json`, 'utf8')) as Scenario);

const paradise = publicCity('paradise');

/** Twelve hours, not the 48 of the horizon: t90 falls before four in every run here, and a
 *  scenario that strands one vehicle would otherwise tick out the whole horizon for nothing. */
const UNTIL = 12 * HOUR;

// Memoised because the same six runs are asked for by several checks, and each is seconds of
// simulated evacuation. Without this the suite outran vitest's timeout, and a timed-out
// `it.fails` reads as an expected failure -- V8 was reported as missing when it does not.
const cache = new Map<string, Metrics>();

function go(name: string, patch: Partial<Scenario['routing']> = {}): Metrics {
  const key = `${name}|${patch.informed ?? ''}`;
  const hit = cache.get(key);
  if (hit) return hit;
  const s0 = preset(name);
  const p = resolveParams({ ...s0, routing: { ...s0.routing, ...patch } });
  const s = createSim(paradise, p, s0.edits);
  s.maxFlowVehH = maxFlow(paradise, p, s.blocked, s.lanes).valueVehH;
  run(s, UNTIL, { frameEvery: 60 });
  const m = metrics(s);
  cache.set(key, m);
  return m;
}

// Warmed here rather than lazily inside the checks: each run is seconds, vitest allows five
// per test by default, and a timed-out `it.fails` reads as an expected failure.
beforeAll(() => {
  go('bare');
  go('paradise-open-network');
  go('paradise-2018');
  go('paradise-2018', { informed: 1 });
  go('paradise-no-contraflow');
}, 120_000);

// -------------------------------------------------------------------- 3.1 static checks

describe('V1: the demand', () => {
  it('totalVeh lands in 9500-12800 at occupancy 2.2', () => {
    const s = createSim(paradise, resolveParams(preset('paradise-2018')));
    expect(s.totalVeh).toBeGreaterThanOrEqual(9500);
    expect(s.totalVeh).toBeLessThanOrEqual(12800);
  });
});

describe('V2: the ceiling', () => {
  const bare = () => {
    const p = resolveParams(normalizeScenario({ city: 'paradise' }));
    const s = createSim(paradise, p);
    return maxFlow(paradise, p, s.blocked, s.lanes).valueVehH;
  };

  // MISSES, by 1%. V2 is written as "without edits and closures", and its 6000-14000 comes
  // from Table 6's seven lanes -- but that table's caption says its lane counts already
  // account for contraflow. Without contraflow Table 6 implies five lanes (Skyway 2, Clark 1,
  // Neal 1, Pentz 1), and five lanes price out at exactly 5940 veh/h. The graph is right; the
  // target was computed for a different network from the one V2 names.
  it.fails('maxFlowVehH of the untouched network lands in 6000-14000', () => {
    expect(bare()).toBeGreaterThanOrEqual(6000);
  });

  it('the untouched network prices out at the five lanes Table 6 implies', () => {
    expect(bare()).toBe(5940);
  });

  it('with the contraflow of Table 6 the ceiling lands in 6000-14000', () => {
    const s0 = preset('paradise-open-network');
    const p = resolveParams(s0);
    const s = createSim(paradise, p, s0.edits);
    const v = maxFlow(paradise, p, s.blocked, s.lanes).valueVehH;
    expect(v).toBeGreaterThanOrEqual(6000);
    expect(v).toBeLessThanOrEqual(14000);
  });
});

describe('V3: the exits', () => {
  it('the graph has exactly four, one per artery of Table 6', () => {
    expect(paradise.X).toBe(4);
    const fed = new Set<string>();
    for (let e = 0; e < paradise.E; e++) {
      if (paradise.flags[e] & FLAG.EXIT_EDGE) fed.add(paradise.nameOf(e));
    }
    expect([...fed].sort()).toEqual([...ARTERIES].sort());
  });
});

describe('V4: the minimum cut', () => {
  it('runs along the exit arteries, not through the residential blocks', () => {
    const p = resolveParams(normalizeScenario({ city: 'paradise' }));
    const s = createSim(paradise, p);
    const cut = maxFlow(paradise, p, s.blocked, s.lanes).cutEdges;
    expect(cut.length).toBeGreaterThan(0);
    for (const e of cut) {
      expect(classOf(paradise.flags[e])).toBeLessThanOrEqual(CLASS_CODE.tertiary);
      expect(ARTERIES).toContain(paradise.nameOf(e));
    }
  });
});

// -------------------------------------------------------------------- 3.2 dynamics

describe('V5: the open network', () => {
  // The falsification criterion of §3.2: under 1.5 h or over 12 h and the model is wrong,
  // and that is not an invitation to turn satFlowPerLane.
  it('t90 lands in 2-4.5 hours', () => {
    const t90 = go('paradise-open-network').t90Sec;
    expect(t90).not.toBeNull();
    expect(t90! / HOUR).toBeGreaterThanOrEqual(2);
    expect(t90! / HOUR).toBeLessThanOrEqual(4.5);
  });
});

describe('V6: the network the fire left', () => {
  // MISSES, low: 3.45 h against 4.5-7.5 h. The schedule is the five-event timeline of
  // VALIDATION.md §2.1, not Table 29's per-artery quarter hours -- the PDF that table lives
  // in is not in this repository, and a schedule reconstructed from a text layer would be
  // invention. A closure here also only removes an artery's last edge, so the network reroutes
  // around it in one field rebuild, where a real burnover took the road and the cars on it.
  // Provisional until Table 29 is transcribed.
  it.fails('t90 lands in 4.5-7.5 hours', () => {
    const t90 = go('paradise-2018').t90Sec;
    expect(t90! / HOUR).toBeGreaterThanOrEqual(4.5);
  });

  it('the closures still cost more than an hour of clearance', () => {
    const t90 = go('paradise-2018').t90Sec;
    expect(t90).not.toBeNull();
    expect(t90! / HOUR).toBeGreaterThan(3);
  });
});

describe('V7: closures must hurt', () => {
  it('t90 with the schedule is strictly worse than without it', () => {
    expect(go('paradise-2018').t90Sec!).toBeGreaterThan(go('paradise-open-network').t90Sec!);
  });
});

describe('V8: the Skyway contraflow', () => {
  it('removing it makes t90 grow', () => {
    expect(go('paradise-no-contraflow').t90Sec!).toBeGreaterThan(go('paradise-2018').t90Sec!);
  });

  // Only once the fire has taken the other arteries. On the open network the contraflow is
  // worth nothing at all -- t90 is the same to the second -- because Skyway never saturates
  // there: it peaks at 1880 veh/h against a capacity of 2520 while Clark Road and Pentz Road
  // sit at theirs. An exit here is the town line, so all four are equally good and the
  // drivers spread over them; Table 6 gave Skyway four of the town's seven lanes, which says
  // the real evacuation did not spread. The bbox is the reason, and it is in LIMITATIONS.
  it('is worth nothing while all four arteries are open', () => {
    expect(go('paradise-open-network').t90Sec).toBe(go('bare').t90Sec);
  });

  it('it does raise the ceiling, so the intervention itself works', () => {
    const of = (name: string) => {
      const s0 = preset(name);
      const p = resolveParams(s0);
      const s = createSim(paradise, p, s0.edits);
      return maxFlow(paradise, p, s.blocked, s.lanes).valueVehH;
    };
    expect(of('paradise-2018')).toBeGreaterThan(of('paradise-no-contraflow'));
  });
});

describe('V12: the information switch', () => {
  it('drivers who see the jams clear the town faster', () => {
    const blind = go('paradise-2018').t90Sec!;
    const seeing = go('paradise-2018', { informed: 1 }).t90Sec!;
    expect(seeing).toBeLessThan(blind);
  });
});

describe('§14.9 holds on a real city with edits', () => {
  it('the simulation never beats its own ceiling', () => {
    for (const name of ['paradise-2018', 'paradise-open-network', 'paradise-no-contraflow']) {
      const m = go(name);
      expect(m.peakOutflowVehH).toBeLessThanOrEqual(m.maxFlowVehH * 1.02);
    }
  });
});
